version = 0.1

[default]
[default.deploy]
stack_name = "my-fitness-app-api"
region = "ap-southeast-2"
s3_prefix = "my-fitness-app-api"
resolve_s3 = true
capabilities = ["CAPABILITY_IAM"]
confirm_changeset = false