AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: FitX API - AWS SAM template for Express on Lambda + API Gateway (HTTP API)

Globals:
  Function:
    Timeout: 30
    MemorySize: 2048
    Architectures:
      - arm64
    Environment:
      Variables:
        NODE_ENV: production
        NODE_OPTIONS: --enable-source-maps
        # Allow Amplify domains by default; you can override with a specific domain later
        CORS_ORIGIN: .amplifyapp.com
        # Optional: set one or both to your frontend URL for CORS allowlist in the app
        WEB_URL: ""
        FRONTEND_URL: ""
        # Secrets are loaded at runtime from SSM and Secrets Manager
        SSM_DATABASE_URL_PARAM: "/my-fitness-app/DATABASE_URL"
        SSM_JWT_SECRET_PARAM: "/my-fitness-app/JWT_SECRET"
        SECRETS_OPENAI_API_KEY_NAME: "my-fitness-app/OPENAI_API_KEY"

Resources:
  AppHttpApi:
    Type: AWS::Serverless::HttpApi
    Properties:
      CorsConfiguration:
        AllowMethods: ['*']
        AllowHeaders: ['*']
        AllowOrigins: ['*']

  ApiFunction:
    Type: AWS::Serverless::Function
    Properties:
      PackageType: Zip
      CodeUri: server
      Handler: lambda-handler.handler
      Runtime: nodejs20.x
      Events:
        ProxyApi:
          Type: HttpApi
          Properties:
            ApiId: !Ref AppHttpApi
            Path: /{proxy+}
            Method: ANY
        RootApi:
          Type: HttpApi
          Properties:
            ApiId: !Ref AppHttpApi
            Path: /
            Method: ANY
      Policies:
        - AWSLambdaBasicExecutionRole
        - Statement:
            - Effect: Allow
              Action:
                - ssm:GetParameter
                - ssm:GetParameters
              Resource:
                - !Sub "arn:aws:ssm:${AWS::Region}:${AWS::AccountId}:parameter/my-fitness-app/*"
            - Effect: Allow
              Action:
                - secretsmanager:GetSecretValue
              Resource:
                - !Sub "arn:aws:secretsmanager:${AWS::Region}:${AWS::AccountId}:secret:my-fitness-app/*"

Outputs:
  ApiUrl:
    Description: Base URL of the HTTP API
    Value: !Sub "https://${AppHttpApi}.execute-api.${AWS::Region}.amazonaws.com"