version: "3.9"
services:
  db:
    image: postgres:16-alpine
    container_name: fitx-postgres
    environment:
      POSTGRES_USER: fitx
      POSTGRES_PASSWORD: fitx
      POSTGRES_DB: fitx
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U fitx"]
      interval: 5s
      timeout: 3s
      retries: 5
volumes:
  pgdata:
