name: Deploy Backend (SAM)

on:
  push:
    branches: [ "main" ]
    paths:
      - "template.yaml"
      - "lambda/**"
      - "server/**"
      - "package.json"
      - "package-lock.json"
      - ".github/workflows/deploy-backend.yml"
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

env:
  AWS_REGION: ap-southeast-1
  STACK_NAME: my-fitness-app-api
  # Optional: provide comma-separated lists to enable VPC for Lambda
  # Example:
  # VPC_SUBNET_IDS: subnet-aaaa,subnet-bbbb
  # VPC_SG_IDS: sg-xxxxxxxx
  VPC_SUBNET_IDS: "subnet-0dc446f73f6492723,subnet-0b6932f3c1ac24bce"
  VPC_SG_IDS: "sg-0db339984913cccf7"

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Configure AWS credentials (OIDC)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_DEPLOY_ROLE_ARN }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Install AWS SAM CLI (pipx)
        run: |
          python3 -m pip install --user pipx
          python3 -m pipx ensurepath
          echo "$HOME/.local/bin" >> "$GITHUB_PATH"
          pipx install aws-sam-cli
      - name: Verify SAM CLI
        run: sam --version

      - name: Install dependencies (server only)
        run: |
          # 1) Install with dev deps to allow prisma generate
          npm --prefix server ci
          npm --prefix server run prisma:generate
          
          # 2) Remove dev deps and heavy, unused Prisma engines to shrink package size
          npm --prefix server prune --omit=dev
          rm -rf server/node_modules/prisma || true
          rm -rf server/node_modules/@prisma/engines || true

      - name: Show server folder size (debug)
        run: du -sh server || true

      - name: SAM Build
        run: sam build

      - name: SAM Deploy
        run: |
          PARAMS=""
          if [ -n "${VPC_SUBNET_IDS}" ] && [ -n "${VPC_SG_IDS}" ]; then
            PARAMS="--parameter-overrides VpcSubnetIds=${VPC_SUBNET_IDS} VpcSecurityGroupIds=${VPC_SG_IDS}"
          fi
          sam deploy \
            --stack-name "$STACK_NAME" \
            --resolve-s3 \
            --capabilities CAPABILITY_IAM \
            --region "$AWS_REGION" \
            --no-confirm-changeset \
            --no-fail-on-empty-changeset \
            $PARAMS

      - name: Show API URL
        run: |
          URL=$(aws cloudformation describe-stacks --stack-name "$STACK_NAME" --query "Stacks[0].Outputs[?OutputKey=='ApiUrl'].OutputValue" --output text --region "$AWS_REGION")
          echo "API URL: $URL"