name: Deploy Backend (SAM)

on:
  push:
    branches: [ "main" ]
    paths:
      - "template.yaml"
      - "lambda/**"
      - "server/**"
      - "package.json"
      - "package-lock.json"
      - ".github/workflows/deploy-backend.yml"
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

env:
  AWS_REGION: ap-southeast-2
  STACK_NAME: my-fitness-app-api

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Configure AWS credentials (OIDC)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_DEPLOY_ROLE_ARN }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Setup AWS SAM CLI
        uses: aws-actions/setup-sam@v2
        with:
          version: "1.*"

      - name: Install dependencies (server only)
        run: |
          npm --prefix server ci
          npm --prefix server run prisma:generate

      - name: SAM Build
        run: sam build

      - name: SAM Deploy
        run: |
          sam deploy \
            --stack-name "$STACK_NAME" \
            --resolve-s3 \
            --capabilities CAPABILITY_IAM \
            --region "$AWS_REGION" \
            --no-confirm-changeset \
            --no-fail-on-empty-changeset

      - name: Show API URL
        run: |
          URL=$(aws cloudformation describe-stacks --stack-name "$STACK_NAME" --query "Stacks[0].Outputs[?OutputKey=='ApiUrl'].OutputValue" --output text --region "$AWS_REGION")
          echo "API URL: $URL"